# Generated by Django 2.2.4 on 2020-10-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(auto_created=True, blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(auto_created=True, default=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('department', models.CharField(default='', max_length=30)),
                ('is_asset_manager', models.BooleanField(default=False)),
                ('is_system_manager', models.BooleanField(default=False)),
                ('is_it_manager', models.BooleanField(default=False)),
            ],
        ),
    ]
