# Generated by Django 2.2.4 on 2020-10-20 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201020_1742'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('ASSET', '资产管理员'), ('SYSTEM', '系统管理员'), ('IT', 'IT管理员'))},
        ),
    ]
