# Generated by Django 2.2.4 on 2020-11-01 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(choices=[('REQUIRE', '领用'), ('MAINTAIN', '维修'), ('TRANSFER', '转移'), ('RETURN', '退库')], max_length=10)),
                ('status', models.CharField(choices=[('DOING', '进行中'), ('SUCCESS', '成功'), ('FAIL', '失败')], default='DOING', max_length=10)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Asset', verbose_name='资产')),
            ],
        ),
    ]
