# Generated by Django 2.2.4 on 2020-11-13 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(auto_created=True, choices=[('DOING', '进行中'), ('SUCCESS', '成功'), ('FAIL', '失败')], default='DOING', max_length=10)),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='发起时间')),
                ('type_name', models.CharField(choices=[('MAINTAIN', '维修'), ('TRANSFER', '转移'), ('RETURN', '退库')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequireIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(auto_created=True, choices=[('DOING', '进行中'), ('SUCCESS', '成功'), ('FAIL', '失败')], default='DOING', max_length=10)),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='发起时间')),
                ('reason', models.TextField(verbose_name='申请理由')),
                ('asset', models.ManyToManyField(related_name='被领用资产', to='asset.Asset')),
                ('asset_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='领用资产类型', to='asset.AssetCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
