# Generated by Django 2.2.4 on 2020-11-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(auto_created=True, choices=[('DOING', '进行中'), ('SUCCESS', '成功'), ('FAIL', '失败')], default='DOING', max_length=10),
        ),
        migrations.AlterField(
            model_name='requireissue',
            name='status',
            field=models.CharField(auto_created=True, choices=[('DOING', '进行中'), ('SUCCESS', '成功'), ('FAIL', '失败')], default='DOING', max_length=10),
        ),
    ]
