# Generated by Django 2.2.4 on 2020-10-31 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='type_name',
            field=models.CharField(choices=[('REQUIRE', '领用'), ('MAINTAIN', '维修'), ('TRANSFER', '转移'), ('RETURN', '退库')], max_length=10),
        ),
    ]
