# Generated by Django 2.2.4 on 2020-11-13 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset', '0002_auto_20201113_1550'),
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requireissue',
            name='handler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_requireissue_hanlder', to=settings.AUTH_USER_MODEL, verbose_name='处理者'),
        ),
        migrations.AddField(
            model_name='requireissue',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_requireissue_initiator', to=settings.AUTH_USER_MODEL, verbose_name='发起者'),
        ),
        migrations.AddField(
            model_name='issue',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset.Asset', verbose_name='资产'),
        ),
        migrations.AddField(
            model_name='issue',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignee', to=settings.AUTH_USER_MODEL, verbose_name='被分配者'),
        ),
        migrations.AddField(
            model_name='issue',
            name='handler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_issue_hanlder', to=settings.AUTH_USER_MODEL, verbose_name='处理者'),
        ),
        migrations.AddField(
            model_name='issue',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_issue_initiator', to=settings.AUTH_USER_MODEL, verbose_name='发起者'),
        ),
    ]
