# Generated by Django 2.2.4 on 2020-11-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0002_auto_20201031_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('DOING', '进行中'), ('SUCCESS', '成功'), ('FAIL', '失败')], default='DOING', max_length=10),
        ),
    ]
