# Generated by Django 2.2.4 on 2020-11-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0002_auto_20201108_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='requireissue',
            name='reason',
            field=models.TextField(default='', verbose_name='申请理由'),
            preserve_default=False,
        ),
    ]
