# Generated by Django 2.2.4 on 2020-10-24 14:08

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('nid', models.AutoField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='nid')),
                ('name', models.CharField(max_length=30, verbose_name='资产名称')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('value', models.IntegerField(default=1, verbose_name='资产价值')),
                ('is_quantity', models.BooleanField(default=False, verbose_name='资产类型')),
                ('description', models.CharField(blank=True, default='', max_length=50, verbose_name='简介')),
                ('parent', models.CharField(blank=True, default='', max_length=20, verbose_name='父资产')),
                ('child', models.CharField(blank=True, default='', max_length=100, verbose_name='子资产')),
                ('status', models.CharField(choices=[('IDLE', 'idle'), ('IN_USE', 'in_use'), ('IN_MAINTAIN', 'in_maintain'), ('RETIRED', 'retired'), ('DELETED', 'deleted')], default='IDLE', max_length=20)),
                ('owner', models.CharField(default='', max_length=30, verbose_name='挂账人')),
                ('department', models.CharField(default='', max_length=30, verbose_name='部门')),
                ('start_time', models.DateTimeField(null=True, verbose_name='录入时间')),
            ],
        ),
        migrations.CreateModel(
            name='AssetCatagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='资产分类')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.AssetCatagory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
