# Generated by Django 2.2.4 on 2020-10-26 02:48

from django.conf import settings
from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(on_delete=models.SET(users.models.User.admin), to=settings.AUTH_USER_MODEL, verbose_name='挂账人'),
        ),
    ]
