# Generated by Django 2.2.4 on 2020-10-28 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asset', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalasset',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='挂账人'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asset.AssetCategory'),
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='asset.AssetCategory', verbose_name='资产分类'),
        ),
        migrations.AddField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(on_delete=models.SET(users.models.User.admin), to=settings.AUTH_USER_MODEL, verbose_name='挂账人'),
        ),
    ]
