# Generated by Django 2.2.4 on 2020-10-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='child',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='子资产'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='parent',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='父资产'),
        ),
    ]
