# Generated by Django 2.2.4 on 2020-10-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='ty',
            new_name='type_name',
        ),
        migrations.RenameField(
            model_name='historicalasset',
            old_name='ty',
            new_name='type_name',
        ),
    ]
