# Generated by Django 2.2.4 on 2020-10-31 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20201030_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCustomAttr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CustomAttr',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='属性名')),
            ],
        ),
    ]
