# Generated by Django 2.2.4 on 2020-10-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20201026_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetcategory',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='资产分类'),
        ),
    ]
