# Generated by Django 2.2.4 on 2020-10-26 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20201026_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicalasset',
            name='changed_by',
        ),
    ]
