# Generated by Django 2.2.4 on 2020-10-26 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_asset_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='简介'),
        ),
    ]
