# Generated by Django 2.2.4 on 2020-11-05 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20201105_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='historicalasset',
            name='category',
        ),
        migrations.RemoveField(
            model_name='historicalasset',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='historicalasset',
            name='service_life',
        ),
        migrations.RemoveField(
            model_name='historicalasset',
            name='value',
        ),
    ]
