# Generated by Django 2.2.4 on 2020-10-27 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20201027_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='service_life',
            field=models.IntegerField(default=1, verbose_name='使用年限'),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='service_life',
            field=models.IntegerField(default=1, verbose_name='使用年限'),
        ),
    ]
